### ISSUE TITLE
[1.19.2][Bug]: crash with secretblocks half slab

### ISSUE THREAD

**Issue by netcore10** [JackGlobetrotter/Full-Slabs#13]
### Full-Slabs Version

latest 

### Minecraft Version

1.19.2

### Fabric Loader Version

0.14.22

### Fabric API Version

0.76.1

### What happened?

Placing down secret slab with fullslabs causes a render crash

### latest.log

[crash-2023-09-30_16.53.26-client.txt](https://github.com/JackGlobetrotter/Full-Slabs/files/12775625/crash-2023-09-30_16.53.26-client.txt)

### Did you isolate Full-Slabs?

I tried Full-Slabs alone

**Comment by JackGlobetrotter** [comment]
hey, what mod are you using for secret slabs ? Please post a log only running fullslabs mod and the mod implementing secret slab.

**Comment by netcore10** [comment]
we were also on a server. it was https://www.curseforge.com/minecraft/mc-mods/secret-rooms-fabric

**Comment by JackGlobetrotter** [comment]
does this issue only happen on the server or locally too ? If so, please provid a log only running fullslabs and secret room mod ! And a crash log while only running these mods.
Are you running fabric or quilt ?

**Comment by netcore10** [comment]
I just realised i tagged as fabric, then realised i was on the wrong one. it's getting harder to test due to the community but it defintely seems like it could be server side. On their own it seems to work fine in sp, i suppose i just need to figure this out slowly

**Comment by JackGlobetrotter** [comment]
May be a mod incompatibility with something else... feel free to reopen the issu if you have any news !
