### ISSUE TITLE
[1.19.12][Crash]: CustomControl issue

### ISSUE THREAD

**Issue by GamerTable** [JackGlobetrotter/Full-Slabs#15]
### Full-Slabs Version

3.3.6

### Minecraft Version

1.19.2

### Fabric Loader Version

0.14.23

### Fabric API Version

0.76.1

### What happened?

If you press the toggleable vertical slabs keybind before having placed any slabs on your current session the game crashes. 

### crash-log

https://gist.github.com/GamerTable/418adf544281d644ef0d53c1f91f3709

### latest.log

https://gist.github.com/GamerTable/b9de10e696d22749d90ed43c2837b725

### Did you isolate Full-Slabs?

I did not try Full-Slabs alone

**Comment by JackGlobetrotter** [comment]
Please install malilib to fix UI overlay issues and let me know how it goes.

**Comment by JackGlobetrotter** [comment]
Nice catch, fixed in e3bba83

**Comment by JackGlobetrotter** [comment]
Nice catch, fixed in https://github.com/JackGlobetrotter/Full-Slabs/commit/e3bba83a045598c18a4a07692cc3cf243673663a
