### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by Donastria** [JackGlobetrotter/Full-Slabs#4]
It keeps crashing the game out and then related to this mod, at the very top of the crash report is this:

[crash-2023-04-18_22.27.40-server.txt](https://github.com/JackGlobetrotter/Full-Slabs/files/11268119/crash-2023-04-18_22.27.40-server.txt)

**Comment by JackGlobetrotter** [comment]
Hey, saw your issue over on curseforge, please poste a log output with only fullslabs mod and litematica/sodium. 
Will look into it when i got some time.

**Comment by JackGlobetrotter** [comment]
Stale issue, please open again if you have any news.
