### ISSUE TITLE
Game crashes immediately after I stack two slabs

### ISSUE THREAD

**Issue by Mahero-Akademiya** [JackGlobetrotter/Full-Slabs#5]
Everything works fine when I launch the game, same when I place a vertical slab, but once I stack two different slabs, the game crashes immediately and close. I tried with my other mods enabled, then disabled, same problem.

In the first log are activated : 
Mods :
- Sodium
- Cloth Config
- Fabric API
- Balm
- Iris Shaders
- MidnightControls (by Motschen)
- Full Slabs 3.3.8
Ressource pack :
- Better Leaves (by Motschen)
Shaders :
- Complementary Shaders v4 (by EminGTR)

In the second log are activated :
Mods :
- Sodium
- Cloth Config
- Fabric API
- Full Slabs 3.3.8

Here are my logs, I hope I did everything correctly : 
https://gist.github.com/Mahero-Akademiya/e9509ea02fb6d54f42f5f0d8e502f4a0

**Comment by JackGlobetrotter** [comment]
Hey, confirmed incompatibility with sodium mod.

**Comment by JackGlobetrotter** [comment]
Sodium removes the Fabric Rendering Api (`FabricBakedModel`) which is needed for Full-Slabs to work. You have to install Indium (https://modrinth.com/mod/indium) to provide support for the default Fabric Rendering API.  I will add documentation to the mod and the Curseforge page soon. 

BTW: Sodium/Indium causes an culling issue for some vertical slab configurations (https://github.com/Micalobia/Full-Slabs/issues/72).

**Comment by JackGlobetrotter** [comment]
Could you please try out this version @Mahero-Akademiya [](url)
[full-slabs-3.3.10.zip](https://github.com/JackGlobetrotter/Full-Slabs/files/11401389/full-slabs-3.3.10.zip)

**Comment by Mahero-Akademiya** [comment]
I just tested the 3.3.10 with Indium and it worked perfectly fine, thank you so much !
