### ISSUE TITLE
Full Slabs in combination with Mishang Urban Construction breaks WorldEdit

### ISSUE THREAD

**Issue by pastellexists** [JackGlobetrotter/Full-Slabs#6]
With Full Slabs and Mishang Urban Construction installed, the air mask in WorldEdit no longer works. No matter what, it will not find any air in your selected area.

In this screenshot, the selection area is visible using WorldEditCUI, and I've just issued the command `//replace #air sand`
![2023-05-02_20 02 36](https://user-images.githubusercontent.com/6536055/235810180-6073bfad-fc8e-4fa1-88af-07c24209026b.png)

This is only an issue when *both* Full Slabs and Mishang Urban Construction are present. Full Slabs does not break the `#air` mask by itself, nor does Mishang Urban Construction by itself.

Here is a log with both mods loaded where I attempted to use the `#air` mask: https://mclo.gs/BgZhDjL
I've also submitted an issue to Mishang Urban Construction's GitHub.

**Comment by JackGlobetrotter** [comment]
The log you provided references a lot of loaded mods!! Please try to isolate the issue (only run FullSlabs + WE, than FullSlabs + WE + MishangUC). Provide logs for these tests and be sure to run the same commands.
BTW: In the log provided, FullSlabs mod is DISABLED!

Also: you are using Quilt, but this is a Farbic mod, normally this should not cause any problems but please try on fabric.

**Comment by JackGlobetrotter** [comment]
Stale issue, please open again if you have any news.
