### ISSUE TITLE
Applied Energistics vertical slabs look like regular quartz

### ISSUE THREAD

**Issue by IstasNix** [JackGlobetrotter/Full-Slabs#8]
When placing Certus Quartz and Smooth Certus Quartz slabs vertically, they render as vanilla quartz slabs.
Chiseled Certus Quartz, Cut Certus Quartz, Certus Quartz Brick, and Certus Quartz Pillar slabs all work fine, however.

**Comment by JackGlobetrotter** [comment]
Wont fix in 1.19.X as ae2 will skip 1.19.4, Investigating once mod is updated to 1.20.X

**Comment by JackGlobetrotter** [comment]
Seems to work in 1.20.1. Please let me know!
